os: linux
cache: pip
dist: xenial
language: python
python: "3.7"
jobs:
  include:
    # lint stage
    - name: "Check package metadata"
      stage: lint
      env: TOXENV=pyroma
    - name: "Check package manifest"
      env: TOXENV=manifest
    - name: "Check code style"
      env: TOXENV=flake8
    # docs stage
    - name: "Check RST documentation style"
      stage: docs
      env: TOXENV=doc8
    - name: "Check readme template"
      env: TOXENV=readme
    - name: "Check sphinx build"
      env: TOXENV=docs
    # tests stages
    - name: "Test fast unit tests"
      stage: fast_tests
      env: TOXENV=py
    - name: "Test slow unit tests"
      stage: slow_tests
      env: TOXENV=integration
install:
  - sh -c 'if [ "$TOXENV" = "py" ]; then pip install tox codecov coverage; else pip install tox; fi'
  - sh -c 'if [ "$TOXENV" = "docs" ]; then sudo apt-get install graphviz; fi'
script:
  - tox
after_success:
  - sh -c 'if [ "$TOXENV" = "py" ]; then tox -e coverage-report; codecov; fi'
